[build]
  # Build command runs from root of monorepo
  command = "pnpm install --frozen-lockfile && pnpm --filter website run build"
  # Output directory for SSR Next.js
  publish = "apps/website/.next"
  # Base directory should be the root of the monorepo
  base = "/"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "18"
  # Use pnpm as the package manager
  NPM_FLAGS = "--version"
  YARN_FLAGS = "--version"
  # Required for Next.js monorepo setups
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NEXT_MONOREPO = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Edge function to help with routing
[[edge_functions]]
  path = "/*"
  function = "rewrite"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
